// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbY8UvNJH7VaDM37iPDLuWsIvN8GCvT2A',
    appId: '1:286017392799:android:58fdd1c9f5749f1b2dd2aa',
    messagingSenderId: '286017392799',
    projectId: 'invenmanager-41a2a',
    databaseURL: 'https://invenmanager-41a2a-default-rtdb.firebaseio.com',
    storageBucket: 'invenmanager-41a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKLmWcSzvLxe78EXCjdd3gLpWqoDg53g',
    appId: '1:286017392799:ios:5a2326d2e7beb1962dd2aa',
    messagingSenderId: '286017392799',
    projectId: 'invenmanager-41a2a',
    databaseURL: 'https://invenmanager-41a2a-default-rtdb.firebaseio.com',
    storageBucket: 'invenmanager-41a2a.firebasestorage.app',
    iosBundleId: 'com.example.invenmanager',
  );

}